language: cpp

dist: trusty

env:
  global:
    - CTEST_OUTPUT_ON_FAILURE=1

matrix:
  include:
    - name: "gcc build"
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - libgslcblas  
            - libgsl-dev
            - python-dev
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - make test
